--SUM (DISTINCT [ALL] EXPR);
--NO PODEMOS SUMAR FECHAS CON OTRAS 
--NO PODEMOS SUMAR NOMBRES 

--SUMA LOS SALARIOS DE LOS 107 O MAS EMPLEADOS 
SELECT SUM (SALARY)FROM EMPLOYEES;

SELECT SALARY  
FROM EMPLOYEES
WHERE SALARY IS NULL;

-- SUMA 2 POR CADA EMPLEADO QUE EXITES
SELECT SUM (2) FROM EMPLOYEES;
-- LO MISMO QUE LA ANTERIOR PERO MAS LARGO
SELECT 2 * COUNT (*) FROM EMPLOYEES;

--SUMAME LOS VALORES DISTINTOS DE LA TABLA DE EMPLEADOS 
SELECT SUM (DISTINCT SALARY) FROM EMPLOYEES;

-- SUMAME LAS COMISIONES DISTINTAS DE TABLA EMPLEADOS 
SELECT SUM (DISTINCT commission_pct) FROM EMPLOYEES;

--COUANTO ES EL TIEMPO  TRABAJADO DE LOS EMPLEADOS 
SELECT ROUND (SUM (SYSDATE - HIRE_DATE)/365.25, 2) "Total de años trabajados"
from EMPLOYEES;

