--MIN MAX (DISTING [ALL] EXPRESION)

-- SELECCION DE LAS COMISIONES MINIMAS Y MAXIMAS 

SELECT MIN(COMMISSION_PCT), MAX(COMMISSION_PCT)
FROM EMPLOYEES;

-- FECHA MINIMA Y FECHA MAXIMA DE LA TABLA JOBS HISTORY
SELECT MIN (START_DATE), MAX(END_DATE)
FROM JOB_HISTORY;

-- SI LO TRABAJAMOS CON CADENAS ORDENA ALFAVETICAMENTE 
SELECT MIN(JOB_ID) , MAX(JOB_ID) FROM EMPLOYEES;

--lA FECHA DE CONTRATACION MAS VAJA EL SALARIO MINIMO , LA FECHA MAS ALTA Y EL SALARIO MAS ALTO DE EMPLEADOS DONDE EL ID DE TRABAJO SEA SA_REP
SELECT MIN(HIRE_DATE), MIN(SALARY), MAX (HIRE_DATE), MAX (SALARY)
FROM EMPLOYEES
WHERE JOB_ID='SA_REP';

-- EL PROMEDIO DE LA LONGITUD DE LOS NOMBRES LOS PAISES 
--Y REDONDEO DE LOS NUMEROS ROUND
SELECT ROUND (AVG(LENGTH(country_name)))"Promedio de longitudes "
FROM COUNTRIES;