select* from COUNTRIES;

/*
plsql 
 LOS OBJETOS QUE VAMOS A VER 
 FUNCIONES 
 PROSEDIMIENTOS 
 PACKAGE 
 TRIGGERS 
 

*/
-- ESTO EN ENTORNO PRODUCTIVO NO SE USA - SOLO DE FORMA DIDACTICA 

BEGIN 
DBMS_OUTPUT.PUT_LINE('!HOLA MUNDO ');
DBMS_OUTPUT.PUT_LINE('!HOLA MUNDO!'|| SYSDATE );
END; 


--SYSTANSIS 
--VARIABLE_NAME DATATYPE TEBLA.CAMPO%TYPE;
--EJEMPLOS
VFECHAS EMPLOYEES.HIRE_DATE%TYPE;
VEMPLOYEES_ID EMPLOYEES.EMPLOYEES_ID 


DECLARE
V_MENSAJES VARCHAR2(100):='!HOLA MUNDO';
BEGIN 
  DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
  V_MENSAJE:='CHAU';
  DBMS_OUTPUT.PUT_LINE('v_mensaje');
  END;
  
DECLARE
V_EMPLEADO EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN 
 IF (VID_EMPLEADO IS NULL )THEN 
  DBMS_OUTPUT.PUT_LINE('EMPLOYEE_ID NULO ');
 ELSEIF ('NULO ')
  END;  
  
  
  if (expresion )then 
  elseif ()
  
  -- ROCK LOOP 
  --LOOP 
  --WHILE 
  -- FOR
  
  --EJEMPLO 
DECLARE
VCONTARDOR NUMBRE !=0;
BEGIN 
WHILE (VCONTADOR <10)
LOOP
 DBMS_OUTPUT.PUT_LINE('VALOR DE CONTADOR '||);
 
END;  
    
--FOR   
BEGIN 
FOR I IN 1 
LOOP 
 DBMS_OUTPUT.PUT_LINE('VALOR DE CONTADOR '||);

END;  


--SELECT INTO   select* from COUNTRIES;

/*
plsql 
 LOS OBJETOS QUE VAMOS A VER 
 FUNCIONES 
 PROSEDIMIENTOS 
 PACKAGE 
 TRIGGERS 
 

*/
-- ESTO EN ENTORNO PRODUCTIVO NO SE USA - SOLO DE FORMA DIDACTICA 

BEGIN 
DBMS_OUTPUT.PUT_LINE('!HOLA MUNDO ');
DBMS_OUTPUT.PUT_LINE('!HOLA MUNDO!'|| SYSDATE );
END; 


--SYSTANSIS 
--VARIABLE_NAME DATATYPE TEBLA.CAMPO%TYPE;
--EJEMPLOS
VFECHAS EMPLOYEES.HIRE_DATE%TYPE;
VEMPLOYEES_ID EMPLOYEES.EMPLOYEES_ID 


DECLARE
V_MENSAJES VARCHAR2(100):='!HOLA MUNDO';
BEGIN 
  DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
  V_MENSAJE:='CHAU';
  DBMS_OUTPUT.PUT_LINE('v_mensaje');
  END;
  
DECLARE
V_EMPLEADO EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN 
 IF (VID_EMPLEADO IS NULL )THEN 
  DBMS_OUTPUT.PUT_LINE('EMPLOYEE_ID NULO ');
 ELSEIF ('NULO ')
  END;  
  
  
  if (expresion )then 
  elseif ()
  
  -- ROCK LOOP 
  --LOOP 
  --WHILE 
  -- FOR
  
  --EJEMPLO 
DECLARE
VCONTARDOR NUMBRE !=0;
BEGIN 
WHILE (VCONTADOR <10)
LOOP
 DBMS_OUTPUT.PUT_LINE('VALOR DE CONTADOR '||);
 
END;  
    
    -- EXCE

DECLARE
VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE ;
VLAST_NAME EMPLOYEES.LAST_NAME%TYPE
BEGIN 
SELECT FIRST_NAME, LAST_NAME 
INTO VFIRST_NAME , VLAST_NAME
FROM EMPLOYEES  
WHERE EMPLOYEES_ID IN (100,101);

EXCEPTION WHEN OTHER THEN 
 DBMS_OUTPUT.PUT_LINE('ERROR'|| SQLERRORM);

END;    
  