-- consultas simples 
SELECT * FROM EMPLOYEES;

--DESCRIBE QUE TIPO DE DATOS TIENE LA TABLA 
DESCRIBE JOBS;

-- SELECCIONO DOS COLUMNAS DE LA TABLA JOBS
SELECT JOB_ID, MIN_SALARY
FROM JOBS;

-- GENERANDO ALIAS PARA RESCRIBIR LAS TABLAS EN LAS CONSULTAS
SELECT JOB_ID AS TRABAJOS,
      MIN_SALARY AS SALARIO_MINIMO
FROM JOBS;

-- CON COMILLA DOBLES EN EL ALIAS RESPETA LOS ESPACIOS Y EL TIPO DE DETRA(MINUSCULAS O MAYUSCULAS)
SELECT JOB_ID AS "Trabajo" ,
      MIN_SALARY AS "Salario Minimo"
FROM JOBS;
--distinto para los objetos que sean distintintos a una columpnas
DESC EMPLOYEES;

SELECT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DISTINCT department_id  FROM EMPLOYEES;

-- DISTINCT SE PUEDE USAR CUANDO TENEMOS MAS DE UNA COLUMNAS
--BUSCA LOS DISTINTOS TENIENDO EN CUENTA LAS DOS COLUMNAS
SELECT DISTINCT department_id, JOB_ID  FROM EMPLOYEES;

SELECT * FROM COUNTRIES;

