/*  FUNCIONES */
/* CONCAT*/
/*PARA CONCADENAR DOS CADENDENAS */

SELECT 'ESTA ES UNA CADENA '|| 'OTRA CADENA ' FROM DUAL; 
--CONCAT(X,Y)
SELECT CONCAT('ESTA ES UNA CADENA ', 'OTRA CADENA ') FROM DUAL; 

SELECT CONCAT(CONCAT('UNO ',' DOS '),' TRES ') FROM DUAL;

SELECT CONCAT(CONCAT(FIRST_name, ' '), LAST_NAME) EMPLOYEES_NAME, 
        FIRST_NAME|| ' ' ||LAST_NAME AS EMPLOYEES_NAME_2
FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;