/*  FUNCIONES */
/* CONCAT*/
/*PARA CONCADENAR DOS CADENDENAS */

SELECT 'ESTA ES UNA CADENA '|| 'OTRA CADENA ' FROM DUAL; 
--CONCAT(X,Y)
SELECT CONCAT('ESTA ES UNA CADENA ', 'OTRA CADENA ') FROM DUAL; 

SELECT CONCAT(CONCAT('UNO ',' DOS '),' TRES ') FROM DUAL;

SELECT CONCAT(CONCAT(FIRST_name, ' '), LAST_NAME) EMPLOYEES_NAME, 
        FIRST_NAME|| ' ' ||LAST_NAME AS EMPLOYEES_NAME_2
FROM EMPLOYEES
WHERE DEPARTMENT_ID=30;

/*SYSDATE */
SELECT SYSDATE FROM DUAL;
/*ADD_MONTHS (D,I)*/
/*
ESTA FUNCION AGREGA MESES 
Y PARA RESTARLES MESES HAY QUE USAR EL VALOR -
*/
-- NOS DEVOLVERA LA FECHA ACTUAL , EL MES PASADO , Y UN AÑOS DESPUES DE LA FECHA ACTUAL
SELECT SYSDATE, ADD_MONTHS(SYSDATE, -1) ANTERIOR, 
      ADD_MONTHS(SYSDATE, 12) SIGUIENTE
FROM DUAL; 

--MONTHS_BETWEEN
/*
DEVUELVE LA CANTIDAD DE MESES EXISTENTE ENTRE DOS FECHAS
CON ROUND(REDONDEAMOS NUMEROS)
APARECERAN NUMEROS NEGATIVOS CUANDO LA PRIMERA FECHA ES ANTERIOR AL LA FECHA ACTUAL 
*/

SELECT MONTHS_BETWEEN('31/03/08','30/09/08') FECHA_1,
       ROUND(MONTHS_BETWEEN('11/03/08','30/09/08')) FECHA_2,
       ROUND (MONTHS_BETWEEN('01/03/08','30/09/08')) FECHA_3,
       MONTHS_BETWEEN('31/03/08','30/09/07') FECHA_4
from dual;       

/* LAST_DATE*/
       
       SELECT SYSDATE,
              LAST_DAY (SYSDATE) FIN_DE_MES,
              LAST_DAY (SYSDATE)+ 1 SIGUIENTE
          FROM DUAL;
       
 /* ROUND(D[,FMT]) */
 /*
 LA FUNCION ES PARA REDONDEO DE FECHA
 RECIBE UN ARGUMENTO QUE ES UN FECHA Y UN FORMATO
 NOS A ESPESIFICAR COMO QUEREMOS TRATAR A LA FECHA 
 Y COMO LA VA A MOSTRAR
 
 */
 
   SELECT SYSDATE,ROUND(SYSDATE, 'hh24') ROUND_HOURS,
                  ROUND(SYSDATE) ROUND_DATE, ROUND(SYSDATE, 'MM')NEW_MONTH,
                  ROUND(SYSDATE, 'YY') NEW_YEAR
      FROM DUAL;
      
--trunc  
/*
si con round se reondea con trunc que muestra si redondeo
*/
       
   SELECT SYSDATE,TRUNC(SYSDATE, 'hh24') TRUNC_HOURS,
                  TRUNC(SYSDATE) TRUNC_DATE, ROUND(SYSDATE, 'MM')TRUNC_MONTH,
                  TRUNC(SYSDATE, 'YY') NEW_YEAR
  FROM DUAL;
   /*TO_DATE*/
   --TO_DATE (C(,FMT[NSLPARAM]))
   /*
   CONSISTEN EN EXTRECION DE TIPO CARARTER, UNA MASCARA DE FORMATO 
   ESPESIFICADOR DE IDIOMA
   */
   
   /* VAMOS A MODIFICAR EL FORMATO DE FECHA QU VIENE POR DEFAULT 
      ES TEMPORAL A UNA SESSION. DEPUESDE RESETEAR EL MOTOR VUELVE A LA NORMALIDAD
   */
   
   ALTER SESSION SET nls_date_format ='DD-MON-RR HH24:MI:SS';
   /
   SELECT  TO_DATE('25-DIC-2010') FROM dual;
  /* me funciono DEPENDE DEL IDIOMA DEL SISTEMA*/ 
  
  select TO_DATE('25-DIC','DD-MON') FROM DUAL; 
  
  SELECT TO_DATE ('25-DIC-2010 18:03:45', 'DD-MON-RR HH24:MI:SS')
  FROM DUAL;/* COMO TODOS LOS DATOS ESTAN ACLARADOS NO TOMA DATOS POR DEFECTO*/