--EJERCICIO 1

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%06';

--EJERCICIO 2

SELECT *
FROM EMPLOYEES
WHERE SALARY < 10000;

--EJERCICIO 3

SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%04'
AND SALARY >= 10000;

--EJERCICIO 4

SELECT *
FROM EMPLOYEES E LEFT OUTER JOIN JOBS J ON E.JOB_ID=J.JOB_ID 
RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE J.JOB_TITLE='Programmer' AND HIRE_DATE Like '%05' OR D.DEPARTMENT_NAME='Marketing';

--EJERCICIO 5

SELECT D.DEPARTMENT_NAME, FIRST_NAME, LAST_NAME 
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON D.MANAGER_ID=E.EMPLOYEE_ID;

--EJERCICIO 6

SELECT LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, COUNTRY_NAME, CITY
FROM LOCATIONS L INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
WHERE C.COUNTRY_NAME = 'United States of America' or C.COUNTRY_NAME = 'Canada';

--EJERCICIO 7

SELECT UPPER(L.CITY), COUNTRY_NAME
FROM LOCATIONS L INNER JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID 
WHERE C.COUNTRY_NAME='Italy';

--EJERCICIO 8

INSERT ALL
INTO EMPLOYEES VALUES (501, 'Mateo', 'Porcar', 'MPORCA', 2324592351, '01-AUG-16', 'IT_PROG', 50000, NULL, NULL, 210)
INTO EMPLOYEES VALUES (502, 'Pablo', 'Vallejos', 'PVALLE', 11502345, '01-AUG-16', 'IT_PROG', 50000, NULL, NULL, 210)
INTO EMPLOYEES VALUES (503, 'Nicolas', 'Maldonado', 'NMALDO', 11344632, '01-AUG-16', 'IT_PROG', 50000, NULL, NULL, 210)

SELECT * FROM EMPLOYEES;

--EJERCICIO 9

UPDATE Departments
SET MANAGER_ID=107
WHERE DEPARTMENT_ID=210;

--EJERCICIO 10

UPDATE EMPLOYEES 
SET MANAGER_ID=107 
WHERE EMPLOYEE_ID > 500;