/*
FUNCION SUSTR (c1, x [,y])
funcion de cadena 

recive un argumendto de tipo cadena , un argumento tipo nunero  x  y posicion y 
*/
SELECT SUBSTR('CADENA MUY LARGA ',10 ) FROM DUAL ; 
SELECT SUBSTR('CADENA MUY LARGA DE EJEMPLO  ',10, 7 ) FROM DUAL ; 

SELECT SUBSTR(10000-8,3,2) FROM DUAL; -- LO RESTA Y LE QUITA LUGARES 

SELECT SYSDATE , SUBSTR(SYSDATE,4,3 ) FROM DUAL ; 

SELECT SUBSTR('1#2#3#4#5#6#7',2,7 ) FROM DUAL ; 


/* UNA TABLA DONDE MUESTRE SOLAMENTE LA PRIMERA LETRA DEL NOMBRE Y EL APELLIDO COMPLETO
  Y QUE EN SU NOMBRE TENGA JOB_ID = AD
*/

SELECT 'NOMBRE: '||SUBSTR(FIRST_NAME,1,1)
|| ' .'|| LAST_NAME " NOMBRE"FROM EMPLOYEES
WHERE SUBSTR(JOB_ID,1,2)='AD'; 

/*EJEMPLO DE TAREA REAL COMO DEDBA */

/* 1RO UNA CONSULTA SOBRE UNA VISTA */
-- ENTRAR COMO USUARIOS SYSTEM 
SELECT FILE_NAME 
FROM DBA_DATA_FILES;
