--EJERCICIO 1 
CREATE OR REPLACE
FUNCTION FN_YEAR (FECHA DATE )
RETURN VARCHAR2 
IS 
    VHIRE_DATE  EMPLOYEES.HIRE_DATE%TYPE;
BEGIN
    SELECT hire_date
    INTO VHIRE_DATE
    FROM EMPLOYEES 
    WHERE HIRE_DATE = FECHA;
   
RETURN VHIRE_DATE; 
END FN_YEAR;
/
/*
Elaborar una sentencia SQL que retorne los empleados que ingresaron
en el año 2007 utilizando la función YEAR.

*/
DECLARE
V DATE ;
BEGIN
V :=('2007','YYYY');
SELECT FN_YEAR 
FROM EMPLOYEES 
WHERE HIRE_DATE= V;
END ;

--EJERCICIO 2
